import { DocsetProvider } from '../models';

const defaultDocsets = [
  {
    id: 'react',
    name: 'React',
    description: 'A JavaScript library for building user interfaces',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://reactjs.org/docs/getting-started.html',
    searchConfig: {
      indexName: 'react',
      apiKey: '36221914cce388c46d0420343e0bb32e',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'vue',
    name: 'VueJS',
    description: 'The Progressive JavaScript Framework',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://reactjs.org/docs/getting-started.html',
    searchConfig: {
      indexName: 'vuejs',
      apiKey: 'f49cbd92a74532cc55cfbffa5e5a7d01',
      appId: 'ML0LEBN7FQ',
    },
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'The entire DevOps lifecycle in one application.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.gitlab.com/',
    searchConfig: {
      indexName: 'gitlab',
      apiKey: 'ce1690e1421303458a1fcbea0cc4a927',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'cypress',
    name: 'Cypress',
    description: 'Test. Automate. Accelerate',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.cypress.io/',
    searchConfig: {
      indexName: 'cypress_docs',
      apiKey: 'b4af59e23bc2fa05281af7dcf13fcae5',
      appId: 'R9KDA5FMJB',
    },
  },
  {
    id: 'tailwindv2',
    name: 'Tailwind (V2)',
    description: 'Rapidly build modern websites without ever leaving your HTML.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://tailwindcss.com/docs/installation/',
    searchConfig: {
      indexName: 'tailwindcss',
      apiKey: '3df93446658cd9c4e314d4c02a052188',
      appId: 'BH4D9OD16A',
      facets: ['version:v2'],
    },
  },
  {
    id: 'tailwindv3',
    name: 'Tailwind (V3)',
    description: 'Rapidly build modern websites without ever leaving your HTML',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://tailwindcss.com/docs/installation/',
    searchConfig: {
      indexName: 'tailwindcss',
      apiKey: '5fc87cef58bb80203d2207578309fab6',
      appId: 'KNPXZI5B0M',
      facets: ['version:v3'],
    },
  },
  {
    id: 'jest',
    name: 'Jest',
    description: 'JavaScript Testing Framework with a focus on simplicity.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://jestjs.io/docs/en/getting-started',
    searchConfig: {
      indexName: 'jest',
      apiKey: '833906d7486e4059359fa58823c4ef56',
      appId: 'BH4D9OD16A',
      facets: ['language:en'],
    },
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    description: 'Vue-powered Static Site Generator ',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://nuxtjs.org/',
    searchConfig: {
      indexName: 'nuxtjs',
      apiKey: 'ff80fbf046ce827f64f06e16f82f1401',
      appId: 'BH4D9OD16A',
      facets: ['tags:en'],
    },
  },
  {
    id: 'vuepress',
    name: 'Vuepress',
    description: 'The Progressive Vue.js Framework',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vuepress.vuejs.org/guide/',
    searchConfig: {
      indexName: 'vuepress',
      apiKey: '3a539aab83105f01761a137c61004d85',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'gatsby',
    name: 'Gatbsy',
    description: 'Blazing fast modern site generator for React.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://www.gatsbyjs.org/docs/',
    searchConfig: {
      indexName: 'gatsbyjs',
      apiKey: '71af1f9c4bd947f0252e17051df13f9c',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'typescript',
    name: 'Typescript',
    description: 'Typed superset of JavaScript that compiles to plain JavaScript.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://www.gatsbyjs.org/docs/',
    searchConfig: {
      indexName: 'typescriptlang',
      apiKey: '3c2db2aef0c7ff26e8911267474a9b2c',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'echo',
    name: 'Echo',
    description: 'High performance, extensible, minimalist Go web framework',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://echo.labstack.com/',
    searchConfig: {
      indexName: 'labstack',
      apiKey: '69dfc65b57ccba29ec34b68aa5b274ed',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'gridsome',
    name: 'Gridsome',
    description: 'Free and open source Vue.js-powered framework for building websites & apps that are fast by default',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://gridsome.org/docs/',
    searchConfig: {
      indexName: 'gridsome',
      apiKey: 'a7400a3a94b256c5283cb05efb860fc1',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'graphql',
    name: 'GraphQL',
    description:
      'Query language for your API, and a server-side runtime for executing queries by using a type system you define for your data',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://graphql.org/learn/',
    searchConfig: {
      indexName: 'graphql',
      apiKey: 'd103541f3e6041148aade2e746ed4d61',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'eslint',
    name: 'ESLint',
    description: 'Find and fix problems in your JavaScript code',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://eslint.org/',
    searchConfig: {
      indexName: 'eslint',
      apiKey: '891b0e977d96c762a3821e0c00172ac9',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'scala',
    name: 'Scala',
    description: 'Scala combines object-oriented and functional programming in one concise, high-level language.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.scala-lang.org/',
    searchConfig: {
      indexName: 'scala-lang',
      apiKey: 'fbc439670f5d4e3730cdcb715c359391',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'webpack',
    name: 'Webpack',
    description: 'Javascript module bundler',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://webpack.js.org/',
    searchConfig: {
      indexName: 'webpack-js-org',
      apiKey: 'fac401d1a5f68bc41f01fb6261661490',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'apollo',
    name: 'Apollo GraphQL',
    description:
      'Platform for building a data graph, a communication layer that seamlessly connects your application clients to your back-end services.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://www.apollographql.com/docs/',
    searchConfig: {
      indexName: 'apollodata',
      apiKey: '768e823959d35bbd51e4b2439be13fb7',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'vuetify',
    name: 'vuetify',
    description: 'Material Design Component Framework',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vuetifyjs.com/en/getting-started/quick-start',
    searchConfig: {
      indexName: 'vuetifyjs',
      apiKey: '259d4615e283a1bbaa3313b4eff7881c',
      appId: 'BH4D9OD16A',
      facets: ['lang:en'],
    },
  },
  {
    id: 'vuex',
    name: 'Vuex',
    description: 'A state management pattern + library for Vue.js applications.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vuex.vuejs.org/',
    searchConfig: {
      indexName: 'vuex',
      apiKey: '97f135e4b5f5487fb53f0f2dae8db59d',
      appId: 'BH4D9OD16A',
      facets: ['lang:en-US'],
    },
  },
  {
    id: 'vue-router',
    name: 'Vue Router',
    description: 'The official router for Vue.js',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://router.vuejs.org/',
    searchConfig: {
      indexName: 'vue-router',
      apiKey: 'f854bb46d3de7eeb921a3b9173bd0d4c',
      appId: 'BH4D9OD16A',
      facets: ['lang:en-US'],
    },
  },
  {
    id: 'parcel',
    name: 'Parcel',
    description: 'Parcel is a web application bundler, differentiated by its developer experience.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vuetifyjs.com/en/getting-started/quick-start',
    searchConfig: {
      indexName: 'parceljs',
      apiKey: '8b6be780425a72d1a1683abea2636778',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'laravel',
    name: 'Laravel',
    description: 'The PHP Framework for Web Artisans',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://laravel.com/docs/8.x/',
    searchConfig: {
      indexName: 'laravel',
      apiKey: '7dc4fe97e150304d1bf34f5043f178c4',
      appId: 'BH4D9OD16A',
      facets: ['version:9.x'],
    },
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    description:
      'A progressive Node.js framework for building efficient, reliable and scalable server-side applications',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.nestjs.com/',
    searchConfig: {
      indexName: 'nestjs',
      apiKey: '9ea53de1a6911255834352bbbe4d3417',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    description: 'Build fast, responsive sites with Bootstrap',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://getbootstrap.com/docs/4.5/getting-started/introduction/',
    searchConfig: {
      indexName: 'bootstrap',
      apiKey: '5990ad008512000bba2cf951ccf0332f',
      appId: 'BH4D9OD16A',
      facets: ['version:4.5'],
    },
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'All in one platform for automating modern web projects.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.netlify.com/',
    searchConfig: {
      indexName: 'docs-manual',
      apiKey: '260466eb2466a36278b2fdbcc56ad7ba',
      appId: '4RTNPM1QF9',
    },
  },
  {
    id: 'babel',
    name: 'Babel',
    description: 'Use next generation JavaScript, today.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://babeljs.io/docs/en/',
    searchConfig: {
      indexName: 'babeljs',
      apiKey: 'd42906b043c5422ea07b44fd49c40a0d',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'gorm',
    name: 'Gorm',
    description: 'The fantastic ORM library for Golang',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://gorm.io/',
    searchConfig: {
      indexName: 'gorm',
      apiKey: '442683d88a109de42c6d01bb0c7c4cec',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'grafana',
    name: 'Grafana',
    description: 'The open and composable observability and data visualization platform',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://grafana.com/docs/grafana/latest/',
    searchConfig: {
      indexName: 'grafana',
      apiKey: '0bd2bd6939038c5ce2c9395732dcf040',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    description: 'Power your metrics and alerting with a leading open-source monitoring solution.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://prometheus.io/docs/',
    searchConfig: {
      indexName: 'prometheus',
      apiKey: '48ac0b7924908a1fd40b1cb18b402ba1',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'prettier',
    name: 'Prettier',
    description: 'Next-generation Node.js and TypeScript ORM',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://prettier.io/docs/en',
    searchConfig: {
      indexName: 'prettier',
      apiKey: '9fcdb2a62af4c47cc5eecf3d5a747818',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'prisma',
    name: 'Prisma',
    description: 'Next-generation Node.js and TypeScript ORM',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://www.prisma.io/docs',
    searchConfig: {
      indexName: 'prisma2-docs',
      apiKey: 'c2c66340c04baad40a878dc3a72fa273',
      appId: 'MK4LNFW4EO',
    },
  },
  {
    id: 'strapi',
    name: 'Strapi',
    description: 'Flexible, open-source Headless CMS',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://strapi.io/documentation',
    searchConfig: {
      indexName: 'strapi',
      apiKey: 'a93451de224096fb34471c8b8b049de7',
      appId: 'BH4D9OD16A',
      facets: ['lang:en-US'],
    },
  },
  {
    id: 'helm',
    name: 'Helm',
    description: 'The package manager for Kubernetes',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.helm.sh/docs',
    searchConfig: {
      indexName: 'helm',
      apiKey: '8bca76b0664b04581dc9f9854e844a90',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'directus',
    name: 'Directus',
    description: 'Open-source Headless CMS with the flexibility and power of a Data API',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.directus.io',
    searchConfig: {
      indexName: 'directus',
      apiKey: '84890d566c1f9ad79ca62a1358e05c60',
      appId: 'BH4D9OD16A',
      facets: ['lang:en-US'],
    },
  },
  {
    id: 'flux',
    name: 'FluxCD',
    description: 'Set of continuous and progressive delivery solutions for Kubernetes',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://fluxcd.io/',
    searchConfig: {
      indexName: 'fluxcd',
      apiKey: '45f9f14d53600b0a2cafa46a26ee10f4',
      appId: 'BH4D9OD16A',
      facets: ['tags:current'],
    },
  },
  {
    id: 'astro',
    name: 'Astro',
    description: 'Modern static site builder.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://docs.astro.build/',
    searchConfig: {
      indexName: 'astro',
      apiKey: '0f387260ad74f9cbf4353facd29c919c',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Platform for frontend frameworks and static sites',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vercel.com/',
    searchConfig: {
      indexName: 'knowledge_production',
      apiKey: '35b6e34b44ca4bcf530d0c4198f58fd8',
      appId: 'NNTAHQI9C5',
    },
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Open source Firebase alternative.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://supabase.com/docs',
    searchConfig: {
      indexName: 'prod_docs',
      apiKey: '0424becc4055d51ec60e54cc37df5574',
      appId: 'B3Z5XYG8NS',
    },
  },
  {
    id: 'nuxt3',
    name: 'Nuxt3',
    description: 'The Hybrid Vue Framework',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://v3.nuxtjs.org/docs',
    searchConfig: {
      indexName: 'nuxtjs',
      apiKey: '60a01900a4b726d667eab75b6f337592',
      appId: '1V8G7N9GF0',
      facets: ['language:en-US', 'tags:v3'],
    },
  },
  {
    id: 'vite',
    name: 'Vite',
    description: 'Next Generation Frontend Tooling',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://v3.nuxtjs.org/docs',
    searchConfig: {
      indexName: 'vitejs',
      apiKey: 'b573aa848fd57fb47d693b531297403c',
      appId: 'BH4D9OD16A',
      facets: ['tags:en'],
    },
  },
  {
    id: 'vitepress',
    name: 'VitePress',
    description: 'Documentation site generator using Vite and Vue',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://vitepress.vuejs.org/',
    searchConfig: {
      indexName: 'vitepress',
      apiKey: 'a18e2f4cc5665f6602c5631fd868adfd',
      appId: '8J64VVRP8K',
    },
  },
  {
    id: 'pinia',
    name: 'Pinia',
    description: 'The Vue Store that you will enjoy using',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://pinia.vuejs.org/',
    searchConfig: {
      indexName: 'pinia',
      apiKey: '45441f4b65a2f80329fd45c7cb371fea',
      appId: '69Y3N7LHI2',
    },
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'Use Cloudflare’s API and edge network',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://developers.cloudflare.com/',
    searchConfig: {
      indexName: 'developers-cloudflare',
      apiKey: 'b23088ab4d346409f9d3ece6606344c3',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'symfony',
    name: 'Symfony',
    description: 'Symfony is a set of reusable PHP components and a PHP framework for web projects',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://symfony.com',
    searchConfig: {
      indexName: 'symfony',
      apiKey: '1a246c2737d8e8c38198dd7ea530d123',
      appId: 'BH4D9OD16A',
      facets: ['version:current'],
    },
  },
  {
    id: 'terraform',
    name: 'Terraform',
    description: 'Terraform codifies cloud APIs into declarative configuration files.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://developer.hashicorp.com/terraform',
    searchConfig: {
      indexName: 'prod_LEARN',
      apiKey: '2cd9898a6c253bfa3965d2b62a4f7f3d',
      appId: 'YY0FFNI7MF',
    },
  },
  {
    id: 'webdev',
    name: 'Web.dev',
    description: 'Take advantage of the latest modern technologies to build amazing web experiences for everyone.',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://web.dev/',
    searchConfig: {
      indexName: 'prod_web_dev',
      apiKey: 'ac32acde5503ed0ab18332e0592e9919',
      appId: '2JPAZHQ6K7',
      facets: ['locales:en'],
    },
  },
  {
    id: 'backstage',
    name: 'Backstage',
    description: 'An open platform for building developer portals',
    enabled: true,
    provider: DocsetProvider.Algolia,
    siteUrl: 'https://backstage.io/docs/',
    searchConfig: {
      indexName: 'backstage',
      apiKey: '8d115c9875ba0f4feaee95bab55a1645',
      appId: 'BH4D9OD16A',
    },
  },
  {
    id: 'nginx-ingress',
    name: 'Nginx Ingress Controller',
    description: 'The NGINX Ingress Controller an implementation of a Kubernetes Ingress Controller for NGINX.',
    enabled: true,
    provider: DocsetProvider.MkDocs,
    siteUrl: 'https://kubernetes.github.io/ingress-nginx',
    searchConfig: {
      indexUrl: 'https://kubernetes.github.io/ingress-nginx/search/search_index.json',
    },
  },
  {
    id: 'argo-cd',
    name: 'ArgoCD',
    description: 'Declarative, GitOps continuous delivery tool for Kubernetes.',
    enabled: true,
    provider: DocsetProvider.MkDocs,
    siteUrl: 'https://argo-cd.readthedocs.io/en/stable',
    searchConfig: {
      indexUrl: 'https://argo-cd.readthedocs.io/en/stable/search/search_index.json',
    },
  },
];

export default defaultDocsets;
